### ISSUE TITLE
`kotlinx.serialization.SerializationException: org.hildan.chrome.devtools.domains.accessibility.AXPropertyName does not contain element with name 'uninteresting'`

### ISSUE THREAD

**Issue by pcarrier** [joffrey-bion/chrome-devtools-kotlin#466]
### Version

6.6.0-1391447

### What happened?

`accessibility.getFullAXTree` throws when called on about any page, eg https://nothing.pcarrier.com

### Reproduction and additional details

```
kotlinx.serialization.SerializationException: org.hildan.chrome.devtools.domains.accessibility.AXPropertyName does not contain element with name 'uninteresting'
	at kotlinx.serialization.json.internal.JsonNamesMapKt.getJsonNameIndexOrThrow(JsonNamesMap.kt:107)
	at kotlinx.serialization.json.internal.JsonNamesMapKt.getJsonNameIndexOrThrow$default(JsonNamesMap.kt:103)
	at kotlinx.serialization.json.internal.AbstractJsonTreeDecoder.decodeTaggedEnum(TreeJsonDecoder.kt:105)
	at kotlinx.serialization.json.internal.AbstractJsonTreeDecoder.decodeTaggedEnum(TreeJsonDecoder.kt:37)
	at kotlinx.serialization.internal.TaggedDecoder.decodeEnum(Tagged.kt:233)
	at kotlinx.serialization.internal.EnumSerializer.deserialize(Enums.kt:136)
	at kotlinx.serialization.internal.EnumSerializer.deserialize(Enums.kt:102)
	at kotlinx.serialization.json.internal.AbstractJsonTreeDecoder.decodeSerializableValue(TreeJsonDecoder.kt:337)
	at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableValue(Tagged.kt:207)
	at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableElement$lambda$1(Tagged.kt:279)
	at kotlinx.serialization.internal.TaggedDecoder.tagBlock(Tagged.kt:294)
	at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableElement(Tagged.kt:279)
	at org.hildan.chrome.devtools.domains.accessibility.AXProperty$$serializer.deserialize(AccessibilityTypes.kt:186)
	at org.hildan.chrome.devtools.domains.accessibility.AXProperty$$serializer.deserialize(AccessibilityTypes.kt:186)
	at kotlinx.serialization.json.internal.AbstractJsonTreeDecoder.decodeSerializableValue(TreeJsonDecoder.kt:337)
	at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableValue(Tagged.kt:207)
	at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableElement$lambda$1(Tagged.kt:279)
	at kotlinx.serialization.internal.TaggedDecoder.tagBlock(Tagged.kt:294)
	at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableElement(Tagged.kt:279)
	at kotlinx.serialization.encoding.CompositeDecoder$DefaultImpls.decodeSerializableElement$default(Decoding.kt:538)
	at kotlinx.serialization.internal.CollectionLikeSerializer.readElement(CollectionSerializers.kt:80)
	at kotlinx.serialization.internal.AbstractCollectionSerializer.readElement$default(CollectionSerializers.kt:51)
	at kotlinx.serialization.internal.AbstractCollectionSerializer.merge(CollectionSerializers.kt:36)
	at kotlinx.serialization.internal.AbstractCollectionSerializer.deserialize(CollectionSerializers.kt:43)
	at kotlinx.serialization.json.internal.AbstractJsonTreeDecoder.decodeSerializableValue(TreeJsonDecoder.kt:337)
	at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableValue(Tagged.kt:207)
	at kotlinx.serialization.internal.TaggedDecoder.decodeNullableSerializableElement$lambda$3(Tagged.kt:288)
	at kotlinx.serialization.internal.TaggedDecoder.tagBlock(Tagged.kt:294)
	at kotlinx.serialization.internal.TaggedDecoder.decodeNullableSerializableElement(Tagged.kt:286)
	at org.hildan.chrome.devtools.domains.accessibility.AXNode$$serializer.deserialize(AccessibilityTypes.kt:324)
[…]
```

### Kotlin target platforms

JVM (non-Android)

**Comment by joffrey-bion** [comment]
Thanks for the report. Which version of Chrome are you using? It seems that this value doesn't exist in the protocol definition:
https://chromedevtools.github.io/devtools-protocol/tot/Accessibility/#type-AXPropertyName

**Comment by pcarrier** [comment]
Also expect `kotlinx.serialization.SerializationException: org.hildan.chrome.devtools.domains.accessibility.AXPropertyName does not contain element with name 'notRendered'`

**Comment by joffrey-bion** [comment]
I think I'll add some lenience here. I never faced any problems with enums so far, but given what you're getting now, I think it's worth introducing an `unknown` synthetic value or something for cases where we get a value from the debugger that we don't know about.

**Comment by pcarrier** [comment]
If maintainers are willing to respond promptly which certainly seems to be the case so far (❤️) I think adding the unknown case to enums that actually prove themselves less thoroughly documented could make sense. If forward compatibility is a goal (support recent versions of Chrome without updating the library) then yes at least anything marked experimental seems worth keeping open to new values.

**Comment by joffrey-bion** [comment]
Thanks! I'm doing my best to react fast, I know what it is to open issues on OSS projects and get no answer for years :)

Regarding forward compatibility, so far I operated under the assumption that I can release timely updates from the tip-of-tree protocol version. And I _do_ release protocol updates from the tip-of-tree rather regularly (except the recent gap due to CI issues).  However, it seems that the current tip-of-tree doesn't contain the values you're describing. So the broken assumption is that the tip-of-tree protocol definitions are perfectly up-to-date.

I checked, and `uninteresting` was never in this enum (at least since 2020), so we can rule out the fact that these values were just deleted from the enum without warning (because of the experimental status). So it does seem that these are new values that just didn't make it to the protocol definition yet (surprising!).

Going with special cases only for enums that turn out problematic will cause friction for users (like you right now). It's probably better to go the forward compatibility route to handle this case. Experimental enums are expected to change a lot. That said, I don't want to clutter stable enums. I think if we ever have a problem with a stable enum, I can indeed take care of it with a special case.

I opened https://github.com/joffrey-bion/chrome-devtools-kotlin/issues/467 to track the solution.

**Comment by joffrey-bion** [comment]
Turns out this specific issue is not new: https://issues.chromium.org/issues/40924391

I wonder why the protocol definition _still_ doesn't include this.
